### ISSUE TITLE
No X, Y, Mt chromosomes after vcfanno

### ISSUE THREAD

**Issue by syouligan** [brentp/vcfanno#110]
Hi Brent

Thanks so much for the fantastic work, I am currently integrating both vcfanno and slivar into our variant analysis pipelines.

One thing I have noticed is that vcfanno is removing X, Y and Mt chromosomes from the vcf output. All are present in the vcf I submit to vcfanno, and in the log files the only mention of these chromosomes is that the X chromosome is absent from one of the annotation files (fathmmXF). I was wondering if you had some insight into how this could be happening, happy to share the files, commands and logs if they will help.

Cheers

Scott

**Comment by brentp** [comment]
hi, it's unlikely that this is happening due to vcfanno (without it showing an error) as it streams over every variant in the input.
what is the complete conf file, the complete command that you ran, and the complete stderr and stdout?

 is this happening for many files, or just one of your test files?

**Comment by syouligan** [comment]
Hi Brent
Thanks for the quick reply. Attached are the command, conf, stderr. The stdout is directing to the results file which is quite large, shall I send this to you via another route along with the input file? This is happening with each sample I run, all stopping at Chr22.
Thanks for your help.

[vcfanno_config_1.conf.txt](https://github.com/brentp/vcfanno/files/3269938/vcfanno_config_1.conf.txt)
[vcfanno_command.txt](https://github.com/brentp/vcfanno/files/3269939/vcfanno_command.txt)
[vcfanno_F02.stderr.txt](https://github.com/brentp/vcfanno/files/3269940/vcfanno_F02.stderr.txt)

**Comment by brentp** [comment]
well, you are getting a panic with this message:
```
panic: strconv.Atoi: parsing "start": invalid syntax
```
so, in one of your files the start column or field has "start" instead of an actual value. it's probably at the end of the file since this error does not occur until late.

you could iteratively try reducing the inputs and see which file causes the failure.

**Comment by syouligan** [comment]
Ok great. In this instance, when you mention files containing a "start" are you referring to the vcf input or the annotation files or either? Thanks for your help.

**Comment by brentp** [comment]
it's like one of the bed or tsv files.

**Comment by syouligan** [comment]
Excellent, found it. Thanks for your help.

**Comment by brentp** [comment]
great. let me know if you have any other issues. and I'm happy to hear feedback on slivar.
